//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramingStudy.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfObject", Namespace="urn:java.lang", ItemName="Object")]
    [System.SerializableAttribute()]
    public class ArrayOfObject : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfObject2D", Namespace="urn:java.lang", ItemName="Object")]
    [System.SerializableAttribute()]
    public class ArrayOfObject2D : System.Collections.Generic.List<ProgramingStudy.ServiceReference1.ArrayOfObject> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DBAWsd/DBAVi", ConfigurationName="ServiceReference1.DBAVi")]
    public interface DBAVi {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:DBAVi) of message selectRequest does not match the default value (urn:DBAWsd/DBAVi)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProgramingStudy.ServiceReference1.ArrayOfObject2D))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProgramingStudy.ServiceReference1.ArrayOfObject))]
        ProgramingStudy.ServiceReference1.selectResponse select(ProgramingStudy.ServiceReference1.selectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramingStudy.ServiceReference1.selectResponse> selectAsync(ProgramingStudy.ServiceReference1.selectRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="select", WrapperNamespace="urn:DBAVi", IsWrapped=true)]
    public partial class selectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DBAVi", Order=0)]
        public string sql;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DBAVi", Order=1)]
        public ProgramingStudy.ServiceReference1.ArrayOfObject @params;
        
        public selectRequest() {
        }
        
        public selectRequest(string sql, ProgramingStudy.ServiceReference1.ArrayOfObject @params) {
            this.sql = sql;
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="selectResponse", WrapperNamespace="urn:DBAVi", IsWrapped=true)]
    public partial class selectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:DBAVi", Order=0)]
        public ProgramingStudy.ServiceReference1.ArrayOfObject2D Response;
        
        public selectResponse() {
        }
        
        public selectResponse(ProgramingStudy.ServiceReference1.ArrayOfObject2D Response) {
            this.Response = Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBAViChannel : ProgramingStudy.ServiceReference1.DBAVi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBAViClient : System.ServiceModel.ClientBase<ProgramingStudy.ServiceReference1.DBAVi>, ProgramingStudy.ServiceReference1.DBAVi {
        
        public DBAViClient() {
        }
        
        public DBAViClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBAViClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBAViClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBAViClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramingStudy.ServiceReference1.selectResponse ProgramingStudy.ServiceReference1.DBAVi.select(ProgramingStudy.ServiceReference1.selectRequest request) {
            return base.Channel.select(request);
        }
        
        public ProgramingStudy.ServiceReference1.ArrayOfObject2D select(string sql, ProgramingStudy.ServiceReference1.ArrayOfObject @params) {
            ProgramingStudy.ServiceReference1.selectRequest inValue = new ProgramingStudy.ServiceReference1.selectRequest();
            inValue.sql = sql;
            inValue.@params = @params;
            ProgramingStudy.ServiceReference1.selectResponse retVal = ((ProgramingStudy.ServiceReference1.DBAVi)(this)).select(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramingStudy.ServiceReference1.selectResponse> ProgramingStudy.ServiceReference1.DBAVi.selectAsync(ProgramingStudy.ServiceReference1.selectRequest request) {
            return base.Channel.selectAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramingStudy.ServiceReference1.selectResponse> selectAsync(string sql, ProgramingStudy.ServiceReference1.ArrayOfObject @params) {
            ProgramingStudy.ServiceReference1.selectRequest inValue = new ProgramingStudy.ServiceReference1.selectRequest();
            inValue.sql = sql;
            inValue.@params = @params;
            return ((ProgramingStudy.ServiceReference1.DBAVi)(this)).selectAsync(inValue);
        }
    }
}
